version: '3.8'

services:
  # PostgreSQL with PostGIS
  db:
    image: postgis/postgis:15-3.3
    container_name: climate_db
    environment:
      POSTGRES_DB: climate_risk_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data/sql:/docker-entrypoint-initdb.d
    restart: unless-stopped

  # FastAPI Backend
  backend:
    build: ./backend
    container_name: climate_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/climate_risk_db
      - CORS_ORIGINS=http://localhost:3000
    volumes:
      - ./data:/app/data
    depends_on:
      - db
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # React Frontend
  frontend:
    build: ./frontend
    container_name: climate_frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped

  # GDAL Processing Service
  gdal-processor:
    build: ./data-processor
    container_name: gdal_processor
    volumes:
      - ./data:/data
    environment:
      - INPUT_PATH=/data/raw
      - OUTPUT_PATH=/data/processed

volumes:
  postgres_data:
